services:
  app:
    build: .
    volumes:
      - .:/app
      - static-data:/app/staticfiles  # Statik fayllar uchun
      - media-data:/app/media  # Media fayllar uchun
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "9400:9400"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static-data:/app/staticfiles  # Statik fayllar
      - media-data:/app/media  # Media fayllar (agar kerak bo‘lsa)
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

volumes:
  static-data:
  media-data:
